version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dev-aws-billing-slack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xxxxxxxxxxxxx"
s3_prefix = "dev-aws-billing-slack"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "EnvironmentName=\"dev\" SlackWebhookUrl=\"\""
